### ISSUE TITLE
interaction vehicle

### ISSUE THREAD

**Issue by LiderDark** [SBDPlugins/Issues-VehiclesPlus#145]
small sugjestion, add an armor stande or invisible slime to create the interaction to open the menu (with a custom location as the wheel or the seat) v3 si vous pouviez ajouter ceci à github en tant que suggestion, cela nous aiderait.

**Comment by stijnb1234** [comment]
V3 will already improve this by forcing users to hold Shift to open the GUI. This makes it possible to use any of the armorstands to open the GUI.
