### ISSUE TITLE
vehicles do not move

### ISSUE THREAD

**Issue by skelegamerYT11** [SBDPlugins/Issues-VehiclesPlus#148]
The vehicles of the VehiclePlusPro plugin version 2.3.5 do not move, here are the logs below
I use Spigot
[latest.log](https://github.com/SBDPlugins/Issues-VehiclesPlus/files/11011239/latest.log)

**Comment by ParadoxPixel** [comment]
Invalid, check: https://github.com/SBDPlugins/Issues-VehiclesPlus/issues/147 for more information
