### ISSUE TITLE
Can't interact with cars spawned with API 3.0.0 pre3.

### ISSUE THREAD

**Issue by JuliGame** [SBDPlugins/Issues-VehiclesPlus#151]
**Describe the bug**  
Cant interact with cars spawned with API 3.0.0 pre3.

**To Reproduce**  
1. Spawn vehicle like so:
```
VehicleModel vehicle = VehiclesPlusAPI.getVehicleModels().get(vehicleName);

StorageVehicle veh = new StorageVehicle(vehicle);

SpawnedVehicle sveh = veh.spawn(spawnLocation.toLocation(owner.getWorld()), false);
```
2. Interact with vehicle spawned

The console outputs this error:
```
Could not pass event PlayerInteractAtEntityEvent to VehiclesPlus v3.0.0-SNAPSHOT
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:143) ~[?:?]
        at nl.sbdeveloper.vehiclesplus.listeners.EntityInteractListener.onClick(EntityInteractListener.java:59) ~[VehiclesPlus-3.0.0-PRE3.jar:?]
```

**Expected behavior**  
The menu should be opened

**Server and Plugin Information**
 - VehiclesPlus Version: 3.0.0 pre3
 - Server Platform and Version [eg: **PaperSpigot** 1.x.x #xxx]: paper 1.19.4

**Comment by stijnb1234** [comment]
The storage vehicle must be saved by hand before you can spawn it. I will provide an example code later today.

**Comment by stijnb1234** [comment]
Correct code:
```java
VehicleModel vehicle = VehiclesPlusAPI.getVehicleModels().get(vehicleName);
StorageVehicle veh = new StorageVehicle(vehicle);
VehiclesPlusAPI.addVehicle(veh, false);
SpawnedVehicle sveh = veh.spawn(spawnLocation.toLocation(owner.getWorld()), false);
```

But the create / delete API will be improved in the near future.
