### ISSUE TITLE
Loading error in version 1.16.5

### ISSUE THREAD

**Issue by gian1carlo** [SBDPlugins/Issues-VehiclesPlus#158]
Loading error in version 1.16.5

When I put the plugin in a more recent version it loads normally, if it doesn't detect the textures the boots item is loaded but when I put it in it doesn't even load the boots item, a stone block is loaded indicating that the file was corrupt.

Try to test it from version 1.16.5 and then to a more recent one.

When trying to buy from the store, it gives an error in the console that the base version of the server appears, it could be that

**Comment by stijnb1234** [comment]
You must get an error at startup too! With your configuration, I got this one:
```
java.lang.IllegalArgumentException: Newer version! Server downgrades are not supported!
```

This means your configurations are for a newer Spigot server version then you are running. The correct one for 1.16.5 should be `2586`. Try changing it in your vehicle configurations files and let me know if this fixed it.

![image](https://github.com/SBDPlugins/Issues-VehiclesPlus/assets/27051051/e2309ec8-ed2e-48cb-9b24-9e5fca626551)
